namespaces:
  - cybnity-local
  - cybnity-dev
  - cybnity-qa
  - cybnity-live
  # To support cert-manager
  - cert-manager

# values authorized: keep, delete
helmResourcePolicy: delete

annotations:
  certmanager.k8s.io/disable-validation: "true"

labels: {}
#labels:
#  additional_label1: myvalue
